image: node:16.17.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli
  - npm install
  - ng build
  - mkdir -p public
  - mv dist/airbnb/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages